apiVersion: apps/v1
kind: Deployment
metadata:
  name: omp-mpi-engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omp-mpi-engine
  template:
    metadata:
      labels:
        app: omp-mpi-engine
    spec:
      nodeSelector:
        kubernetes.io/hostname: vm1
      containers:
      - name: omp-mpi-engine
        image: omp-mpi-engine
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: omp-mpi-engine-service
spec:
  selector:
    app: omp-mpi-engine
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  type: NodePort
