apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: vm1
      containers:
      - name: socket-server
        image: leonardomilv3/socket-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: SPARK_ENGINE_HOST
          value: "spark-engine-service"
        - name: SPARK_ENGINE_PORT
          value: "5000"
        - name: OMP_MPI_ENGINE_HOST
          value: "omp-mpi-engine-service"
        - name: OMP_MPI_ENGINE_PORT
          value: "5000"
        - name: SERVER_PORT
          value: "5000"
        - name: ELASTIC_HOST
          value: "elasticsearch-service"
---
apiVersion: v1
kind: Service
metadata:
  name: socket-server-service
spec:
  selector:
    app: socket-server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30080 
  type: NodePort
